import { Cairo, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "./app-sidebar"
// Ensure Arabic subset is included
const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin", "arabic"], // Add Arabic support
  weight: ["400","500","600", "700", "800"], // Add different font weights if needed
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html lang="ar" dir="rtl">
        <meta
          name="google-site-verification"
          content="aBeBLn0154fF8U59hPrcX7A5liZvYPLgpEFjSvm1Fn8"
        />
    
            <body className={` ${cairo.variable} antialiased`}>
       <SidebarProvider>
        <AppSidebar />
        <main className="flex-1 flex flex-col p-4">
      <SidebarTrigger />
        {children}
        </main>
      </SidebarProvider>

      </body>
    </html>

  );
}
